$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1428737136886.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0143233af1134fa1bf149eb898896a48",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"635e5bdf8cb142799c66f4f39955e480",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":310,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4c08dec696114ea18882351367b9860c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":310},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f3943823d5047f4999f22a9c9b0367c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":310},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 上传文件 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"上传文件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"fae3c4b43b37410f8cff2bf3b98ff75f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":47.5},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad97e78cc333484f9faa00b19b978e6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":47.5},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"b75daee8caf749cab8941f7aa131fa43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":17},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9717102c81548d7b4fba12f3bde361d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":17},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d75616ef3f04cf480dfecb911825a7a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":13},
            "size":{
              "width":72,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bc32d865de6949dd865f76227efb931b",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":90},
            "size":{
              "width":360,
              "height":190}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"40868484855742c6847cd1ca9e9f2669",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0babd86f97024ffdbc0540bd6da6f386",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":100},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"选中一个条目后，下方的“下载”和“删除”按钮才会根据权限变为able或disable"},
          "images":{
            "normal~":"images/主页/u9.png"}},
{
          "id":"d112b8785d7144439492a19e99496fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ef771c15044ce98bf83b548d502727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":130},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u9.png"}},
{
          "id":"32d9b6d0145547a0bf81ac0f0b351fca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":160},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f208910c0c48fe840e8b293af44686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":160},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u9.png"}},
{
          "id":"4835c22160ae42ad868b3978fe7a0c9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":310},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3998ef1af28404a92db5133695c7912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":310},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"a7e9f0c22ea241129c7a8119401fdd63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":310},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d716b0832b2745be9a1e485f754858bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":310},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"dabc12cab7ed40d99371995ed742cc96",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":100},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea95384c87e4daab427d301f0a43d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":100},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"60c33117805d44499c46a443506dc30f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":126},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c9da21a7e1496db0eb3a43be22d812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":126},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2b8e003059b846c2b60cf9decec9accb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":152},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b5a4182e2914a9a9bfb37a0e14e2831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":152},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7e386b306895479688fc754ffc65abcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":190},
            "size":{
              "width":50,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a71895b9504cdb9bf3b764f64cd24b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":190},
                "size":{
                  "width":50,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"在上面的勾选框中选择后，点击刷新按钮更新列表"},
          "images":{
            "normal~":"images/主页/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "635e5bdf8cb142799c66f4f39955e480":{
      "scriptId":"u0"},
    "4c08dec696114ea18882351367b9860c":{
      "scriptId":"u1"},
    "5f3943823d5047f4999f22a9c9b0367c":{
      "scriptId":"u2"},
    "fae3c4b43b37410f8cff2bf3b98ff75f":{
      "scriptId":"u3"},
    "ad97e78cc333484f9faa00b19b978e6f":{
      "scriptId":"u4"},
    "b75daee8caf749cab8941f7aa131fa43":{
      "scriptId":"u5"},
    "f9717102c81548d7b4fba12f3bde361d":{
      "scriptId":"u6"},
    "4d75616ef3f04cf480dfecb911825a7a":{
      "scriptId":"u7"},
    "bc32d865de6949dd865f76227efb931b":{
      "scriptId":"u8"},
    "40868484855742c6847cd1ca9e9f2669":{
      "scriptId":"u9"},
    "0babd86f97024ffdbc0540bd6da6f386":{
      "scriptId":"u10"},
    "d112b8785d7144439492a19e99496fdc":{
      "scriptId":"u11"},
    "a5ef771c15044ce98bf83b548d502727":{
      "scriptId":"u12"},
    "32d9b6d0145547a0bf81ac0f0b351fca":{
      "scriptId":"u13"},
    "83f208910c0c48fe840e8b293af44686":{
      "scriptId":"u14"},
    "4835c22160ae42ad868b3978fe7a0c9d":{
      "scriptId":"u15"},
    "b3998ef1af28404a92db5133695c7912":{
      "scriptId":"u16"},
    "a7e9f0c22ea241129c7a8119401fdd63":{
      "scriptId":"u17"},
    "d716b0832b2745be9a1e485f754858bf":{
      "scriptId":"u18"},
    "dabc12cab7ed40d99371995ed742cc96":{
      "scriptId":"u19"},
    "dea95384c87e4daab427d301f0a43d19":{
      "scriptId":"u20"},
    "60c33117805d44499c46a443506dc30f":{
      "scriptId":"u21"},
    "b7c9da21a7e1496db0eb3a43be22d812":{
      "scriptId":"u22"},
    "2b8e003059b846c2b60cf9decec9accb":{
      "scriptId":"u23"},
    "8b5a4182e2914a9a9bfb37a0e14e2831":{
      "scriptId":"u24"},
    "7e386b306895479688fc754ffc65abcd":{
      "scriptId":"u25"},
    "17a71895b9504cdb9bf3b764f64cd24b":{
      "scriptId":"u26"}}});